# Generated by Django 4.2.13 on 2024-06-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название города', max_length=256, verbose_name='Город')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор города')),
                ('population', models.IntegerField(help_text='Численность населения', verbose_name='Численность')),
                ('size', models.IntegerField(help_text='Площадь города', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название группы меток csv файла', max_length=256, verbose_name='Название метки')),
                ('csv_mark', models.FileField(upload_to='csv_marks')),
                ('city', models.ForeignKey(help_text='Метки для какого города?', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='MapWorker.city', verbose_name='Метки для города')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
    ]
