# Generated by Django 4.2.13 on 2024-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapWorker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='center_x',
            field=models.FloatField(default=1, verbose_name='Координата Х центра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='center_y',
            field=models.FloatField(default=1, verbose_name='Координата Y центра'),
            preserve_default=False,
        ),
    ]
