# Generated by Django 4.2.13 on 2024-06-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapWorker', '0002_city_center_x_city_center_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название слоя')),
                ('csv_layer', models.FileField(upload_to='csv_layers', verbose_name='Загрузить файл')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(verbose_name='Численность'),
        ),
        migrations.AlterField(
            model_name='city',
            name='size',
            field=models.IntegerField(verbose_name='Размер'),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.AddField(
            model_name='layer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='MapWorker.city', verbose_name='Метки для города'),
        ),
    ]
